<<<<<<< HEAD
export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';

export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';

export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
=======
export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';

export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';

export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
>>>>>>> 620ca0de838e67c5ce02a285f6df7d10ae309fa7
